In [1]:
import numpy as np

# Create a 1D array

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [2]:
# check the array

print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
# Check the shape of the array

print(arr1.shape)

(3,)


In [4]:
# accessing elements from the array

arr1[2]

3

In [5]:
# Change an element from the array

arr1[2]= 5

In [6]:
arr1

array([1, 2, 5])

In [7]:
# Create a 2D array

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
# Check the shape of the array

print("The shape is 2 rows and 3 columns:", arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


In [9]:
# Accessing elements from the array

arr2[0][2]

3

In [10]:
arr2[0,2]

3

In [11]:
arr2[0,-2]

2

In [12]:
arr2[0,-1]

3

In [13]:
arr2[-1, 0]

4

In [14]:
# Array of type string

arr3 = np.array(['India', 'China', 'USA' , 'Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [15]:
arr3[1]

'China'

In [16]:
# Array of evenly spaced values within a specified interval

arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [17]:
# Array of evenly spaced number in a specified interval

arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [18]:
# Array of random values between 0 and 1 in a given shape

arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[0.42200819 0.57585171 0.22831627 0.46441064 0.00334638 0.21127962
 0.42194963 0.163801   0.14303295 0.08899656]


[[0.28921797 0.45816524 0.80575906 0.8087363 ]
 [0.61115632 0.26423006 0.46612868 0.54767124]
 [0.85737677 0.07967155 0.23825272 0.66446402]]


In [19]:
# Array of zeros

print(np.zeros(10))
print('\n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# Array of constant values in a given shape

print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [22]:
# Create an array by repetition
# epeat each element of an array by a specified number of times

arr = [0, 1, 2]
print(np.repeat(arr, 3)) 

[0 0 0 1 1 1 2 2 2]


In [23]:
# Repeat an array by a specified number of times

arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [24]:
# Create an idenity matrix

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# Create a matrix with a specified diagonal array

arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [27]:
arr = np.random.rand(5,5)
print(arr)

[[0.99223015 0.17359626 0.16966868 0.88688    0.69983739]
 [0.32259645 0.71849785 0.89785234 0.03866017 0.00305099]
 [0.55643948 0.05942044 0.49586252 0.00128778 0.23396058]
 [0.21752392 0.97095102 0.49166825 0.3222195  0.3836796 ]
 [0.88592398 0.51232878 0.4981844  0.48653906 0.59484215]]


In [28]:
# Extract the diagonal elements in the array
print(np.diag(arr))

[0.99223015 0.71849785 0.49586252 0.3222195  0.59484215]


In [29]:
# Display the length of the array
print(len(arr))

5


In [30]:
# Display the dimension of the array
print(arr.ndim)

2


In [31]:
# Display the size of the elements
print(arr.size)

25


In [32]:
# print 4 random integers

print(np.random.randint(-10, 10, 4))

[  4   6 -10  -9]


In [33]:
# Mathematical operations

print(arr + 10)
print('\n')
print(arr - 10)
print('\n')
print(arr * 10)
print('\n')
print(arr / 10)

[[10.99223015 10.17359626 10.16966868 10.88688    10.69983739]
 [10.32259645 10.71849785 10.89785234 10.03866017 10.00305099]
 [10.55643948 10.05942044 10.49586252 10.00128778 10.23396058]
 [10.21752392 10.97095102 10.49166825 10.3222195  10.3836796 ]
 [10.88592398 10.51232878 10.4981844  10.48653906 10.59484215]]


[[-9.00776985 -9.82640374 -9.83033132 -9.11312    -9.30016261]
 [-9.67740355 -9.28150215 -9.10214766 -9.96133983 -9.99694901]
 [-9.44356052 -9.94057956 -9.50413748 -9.99871222 -9.76603942]
 [-9.78247608 -9.02904898 -9.50833175 -9.6777805  -9.6163204 ]
 [-9.11407602 -9.48767122 -9.5018156  -9.51346094 -9.40515785]]


[[9.92230153 1.7359626  1.69668677 8.86879999 6.99837388]
 [3.22596455 7.1849785  8.97852342 0.38660168 0.03050989]
 [5.56439483 0.59420435 4.95862515 0.01287781 2.33960583]
 [2.17523924 9.70951015 4.91668246 3.22219502 3.83679597]
 [8.85923977 5.12328784 4.98184402 4.86539061 5.94842153]]


[[0.09922302 0.01735963 0.01696687 0.088688   0.06998374]
 [0.03225965 

In [34]:
# Exponentiation

print(np.exp(arr))

[[2.69724303 1.18957519 1.1849122  2.42754388 2.01342527]
 [1.38070806 2.05134946 2.45432639 1.0394172  1.00305565]
 [1.74445028 1.06122132 1.6419138  1.00128861 1.26359468]
 [1.24299517 2.64045438 1.6350416  1.3801877  1.46767512]
 [2.42522421 1.66917382 1.64573057 1.62667664 1.81274479]]


In [35]:
# Natural logarithm

print(np.log(arr))

[[-0.00780019 -1.75102302 -1.7739077  -0.12004559 -0.35690727]
 [-1.1313531  -0.33059257 -0.10774965 -3.25294545 -5.79228936]
 [-0.58619686 -2.82311709 -0.70145658 -6.65483439 -1.45260263]
 [-1.52544644 -0.02947926 -0.70995109 -1.13252228 -0.95794746]
 [-0.12112414 -0.6687887  -0.69678499 -0.72043809 -0.5194592 ]]


In [36]:
# Base 2 logarithm

print(np.log2(arr))

[[-0.0112533  -2.52619223 -2.55920785 -0.17318918 -0.51490835]
 [-1.63219751 -0.47694425 -0.15544989 -4.69300827 -8.35650713]
 [-0.8457033  -4.07289702 -1.01198793 -9.60089657 -2.0956626 ]
 [-2.20075401 -0.04252958 -1.02424291 -1.63388428 -1.38202605]
 [-0.17474519 -0.96485815 -1.00524824 -1.03937246 -0.74942121]]


In [37]:
# Base 10 logarithm

print(np.log10(arr))

[[-0.00338758 -0.76045964 -0.77039833 -0.05213514 -0.15500286]
 [-0.49134041 -0.14357453 -0.04679508 -1.41273626 -2.5155593 ]
 [-0.25458206 -1.22606417 -0.30463872 -2.89015785 -0.6308573 ]
 [-0.66249297 -0.01280268 -0.30832784 -0.49184818 -0.41603129]
 [-0.05260354 -0.29045124 -0.30260987 -0.31288229 -0.22559826]]


In [38]:
# sin function

print(np.sin(arr))

[[0.83724756 0.17272567 0.16885579 0.7751042  0.64409331]
 [0.31703014 0.6582546  0.7819901  0.03865054 0.00305098]
 [0.52816617 0.05938547 0.47579046 0.00128778 0.23183201]
 [0.21581256 0.82542295 0.47209718 0.31667261 0.37433506]
 [0.7744998  0.49020835 0.47783141 0.46756938 0.56037803]]


In [39]:
print(np.sin(180))

-0.8011526357338306


In [40]:
print(np.sin(0))

0.0


In [41]:
# cos function

print(np.cos(arr))

[[0.54682403 0.98496997 0.98564077 0.63183342 0.76494693]
 [0.94841546 0.75279538 0.62329085 0.99925279 0.99999535]
 [0.84914103 0.99823513 0.87955866 0.99999917 0.97275584]
 [0.97643481 0.5645148  0.88154651 0.9485349  0.92729351]
 [0.63257415 0.87160528 0.87845156 0.88395638 0.82823696]]


In [42]:
print(arr)

[[0.99223015 0.17359626 0.16966868 0.88688    0.69983739]
 [0.32259645 0.71849785 0.89785234 0.03866017 0.00305099]
 [0.55643948 0.05942044 0.49586252 0.00128778 0.23396058]
 [0.21752392 0.97095102 0.49166825 0.3222195  0.3836796 ]
 [0.88592398 0.51232878 0.4981844  0.48653906 0.59484215]]


In [43]:
# sum along the row
print(np.sum(arr, axis=0))

[2.97471399 2.43479434 2.55323618 1.73558651 1.91537071]


In [44]:
# sum along the column
print(np.sum(arr, axis=1))

[2.92221248 1.9806578  1.3469708  2.38604228 2.97781838]


In [45]:
# minimum item value along the row
print(np.min(arr))

0.0012877813963096951


In [46]:
print(np.max(arr))

0.9922301525372236


In [47]:
# calculate the overall mean

print(np.mean(arr))

0.46454806958433614


In [48]:
# calculate the mean along the row

print(np.mean(arr, axis=0))

[0.5949428  0.48695887 0.51064724 0.3471173  0.38307414]


In [49]:
# calculate the median
print(np.median(arr))

0.49166824613153004


In [50]:
# calculate the standard deviation
print(np.std(arr))

0.30563359385732


In [51]:
# calculate the variance
print(np.var(arr))

0.09341189369414123


In [52]:
print(arr)
print('\n')
print(arr[1:3, 2:5])

[[0.99223015 0.17359626 0.16966868 0.88688    0.69983739]
 [0.32259645 0.71849785 0.89785234 0.03866017 0.00305099]
 [0.55643948 0.05942044 0.49586252 0.00128778 0.23396058]
 [0.21752392 0.97095102 0.49166825 0.3222195  0.3836796 ]
 [0.88592398 0.51232878 0.4981844  0.48653906 0.59484215]]


[[0.89785234 0.03866017 0.00305099]
 [0.49586252 0.00128778 0.23396058]]


In [53]:
# Sort an array
arr = np.random.rand(5,5)
print(arr)

[[0.35612795 0.50546718 0.1656606  0.06054393 0.84889493]
 [0.22324207 0.90674322 0.98515321 0.27758528 0.61105448]
 [0.93145685 0.1692322  0.26343715 0.53979402 0.81682755]
 [0.17412512 0.80840123 0.85776828 0.41676607 0.00454651]
 [0.8556902  0.23195043 0.83545559 0.51886496 0.10875786]]


In [54]:
# sort along the column

print(np.sort(arr, axis=1))

[[0.06054393 0.1656606  0.35612795 0.50546718 0.84889493]
 [0.22324207 0.27758528 0.61105448 0.90674322 0.98515321]
 [0.1692322  0.26343715 0.53979402 0.81682755 0.93145685]
 [0.00454651 0.17412512 0.41676607 0.80840123 0.85776828]
 [0.10875786 0.23195043 0.51886496 0.83545559 0.8556902 ]]


In [55]:
# Transpose an array
print(arr)
print('\n')
print(arr.T)

[[0.35612795 0.50546718 0.1656606  0.06054393 0.84889493]
 [0.22324207 0.90674322 0.98515321 0.27758528 0.61105448]
 [0.93145685 0.1692322  0.26343715 0.53979402 0.81682755]
 [0.17412512 0.80840123 0.85776828 0.41676607 0.00454651]
 [0.8556902  0.23195043 0.83545559 0.51886496 0.10875786]]


[[0.35612795 0.22324207 0.93145685 0.17412512 0.8556902 ]
 [0.50546718 0.90674322 0.1692322  0.80840123 0.23195043]
 [0.1656606  0.98515321 0.26343715 0.85776828 0.83545559]
 [0.06054393 0.27758528 0.53979402 0.41676607 0.51886496]
 [0.84889493 0.61105448 0.81682755 0.00454651 0.10875786]]


In [56]:
print(arr.transpose())

[[0.35612795 0.22324207 0.93145685 0.17412512 0.8556902 ]
 [0.50546718 0.90674322 0.1692322  0.80840123 0.23195043]
 [0.1656606  0.98515321 0.26343715 0.85776828 0.83545559]
 [0.06054393 0.27758528 0.53979402 0.41676607 0.51886496]
 [0.84889493 0.61105448 0.81682755 0.00454651 0.10875786]]


In [57]:
# Flatten the 2D array

print(arr)
print('\n')
print(arr.flatten())

[[0.35612795 0.50546718 0.1656606  0.06054393 0.84889493]
 [0.22324207 0.90674322 0.98515321 0.27758528 0.61105448]
 [0.93145685 0.1692322  0.26343715 0.53979402 0.81682755]
 [0.17412512 0.80840123 0.85776828 0.41676607 0.00454651]
 [0.8556902  0.23195043 0.83545559 0.51886496 0.10875786]]


[0.35612795 0.50546718 0.1656606  0.06054393 0.84889493 0.22324207
 0.90674322 0.98515321 0.27758528 0.61105448 0.93145685 0.1692322
 0.26343715 0.53979402 0.81682755 0.17412512 0.80840123 0.85776828
 0.41676607 0.00454651 0.8556902  0.23195043 0.83545559 0.51886496
 0.10875786]


In [58]:
# Append elements to an array

arr = np.array([4,5,6,7])

In [59]:
arr1 = np.append(arr, 8)
arr1

array([4, 5, 6, 7, 8])

In [60]:
arr2 = np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [61]:
# Insert elements to an array

arr3 = np.insert(arr, 0, [12,13,14])
print(arr3)

[12 13 14  4  5  6  7]


In [62]:
# Remove elements from an array

print(arr)
print('\n')
arr4 = np.delete(arr, 0)
print(arr4)

[4 5 6 7]


[5 6 7]


In [63]:
# Delete multiple elements

print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [64]:
# Copy elements from an array

arr1 = np.arange(10, 40, 3)
arr1

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [65]:
arr_copy = np.copy(arr1)
arr_copy

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [66]:
arr_copy = arr1.copy()
print(arr_copy)

[10 13 16 19 22 25 28 31 34 37]


In [67]:
# Combine and split an array

arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [68]:
# Combine the array items by row

cat = np.concatenate((arr1,arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [69]:
# Combine array items by column

cat = np. concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [70]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [71]:
# Stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [72]:
# Set operations

# Find elements from an array
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])
print(np.unique(arr))

[1 2 3 4 5 6]


In [73]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [74]:
# Intersection of 2 array elements

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [75]:
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [76]:
# Union of 2 array elements

print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [77]:
# Elements present in first array but not in the second array
print(np.setdiff1d(arr1, arr2))
print(np.setdiff1d(arr2, arr1))

[1 2]
[6 7]


In [78]:
# Elements present in either of the arrays but not both

print(np.setxor1d(arr1, arr2))

[1 2 6 7]
